---
title: "Loops and Functions"
author: "Daniel Kerstan"
date: "8/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Task 1
```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")

transects <- c("TransectA", "TransectB", "TransectC")

task_matrix <- matrix(nrow = length(weekdays), ncol = length(transects))

for (i in seq_along(transects)) {
  for (j in seq_along(weekdays)){
    out <- (paste(weekdays[j], "-", transects[i]))
    task_matrix[j,i] <- out
  }
}

task_matrix
```

Task 2

```{r}
force <- function(m, a) {
  f = m * a
  print(paste("The resulting force is", f, "Newtons"))
}

force(5, 2)
```

Task 3

```{r}
name_column <- function(df, n) {
  if (n < 1) {
    warning("column number must be greater than 1")
  }
  if (n > length(df)) {
    stop("number exceeds amount of columns in data frame")
  }
  return(names(df[n]))
}
name_column(mtcars, 10)
```

Task 4

```{r}
fish_parms <- data.frame(sci_name = c("Chanos chanos", "Sphyraena barracuda", "Caranx ignobilis"), 
                         common_name = c("Milkfish", "Great barracuda", "Giant trevally"),
                         a_est = c(0.0905, 0.0181, 0.0353),
                         b_est = c(2.52, 3.27, 3.05))

fish_weight <- function(fish_name, tot_length){
  if (fish_name == "Milkfish") {
    a <- fish_parms[1,3]
    b <- fish_parms[1,4]
  } else if (fish_name == "Great barracuda") {
    a <- fish_parms[2,3]
    b <- fish_parms[2,4]
  } else if (fish_name == "Giant trevally") {
    a <- fish_parms[3,3]
    b <- fish_parms[3,4]
  }
  W = a * tot_length ^ b
  return(W)
}

fish_weight(fish_name = "Great barracuda", tot_length = 20)

milkfish_weights <- fish_weight(fish_name = "Milkfish", tot_length = seq(from = 0, to = 100, by = 1))

milkfish_weights
```
Task 5


```{r}
wave_power <- function(wave_height, period) {
  P = 0.5 * wave_height ^ 2 * period
  return(P)
}

wave_power(wave_height = seq(from = 0, to = 3, by = 0.2), period = 8)
```
Task 6

```{r}
wave_power_shallow <- function(wave_height_shallow, period_shallow) {
  Pshallow = 0.81 * wave_height_shallow ^ 2 * period_shallow
  return(Pshallow)
}
  
power <- function(depth, height, per) {
  if (depth > 12) {
    deep <- wave_power(wave_height = height, period = per)
     message("deep water equation was used")
    return(deep)
  } else if (depth <= 12) {
    shallow <- wave_power_shallow(wave_height_shallow = height, period_shallow = per)
    message("shallow water equation was used")
    return(shallow)
    
  }
}

power(14, 4, 5)
  
```

